In [13]:
from conexion_bd import df
import pandas as pd
from IPython.display import display

In [5]:
df.shape

(54808, 14)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           54808 non-null  int64
 1   department            54808 non-null  str
 2   region                54808 non-null  str
 3   education             52399 non-null  str
 4   gender                54808 non-null  str
 5   recruitment_channel   54808 non-null  str
 6   no_of_trainings       54808 non-null  int64
 7   age                   54808 non-null  int64
 8   previous_year_rating  50684 non-null  float64
 9   length_of_service     54808 non-null  int64
 10  KPIs_met >80%         54808 non-null  int64
 11  awards_won?           54808 non-null  int64
 12  avg_training_score    54808 non-null  int64
 13  is_promoted           54808 non-null  int64
dtypes: float64(1), int64(8), str(5)
memory usage: 5.9 MB

In [8]:
df.describe()

,employee_id,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
count,54808.000000,54808.000000,54808.000000,50684.000000,54808.000000,54808.000000,54808.000000,54808.000000,54808.000000
mean,39195.830627,1.253011,34.803915,3.329256,5.865512,0.351974,0.023172,63.386750,0.085170
std,22586.581449,0.609264,7.660169,1.259993,4.265094,0.477590,0.150450,13.371559,0.279137
min,1.000000,1.000000,20.000000,1.000000,1.000000,0.000000,0.000000,39.000000,0.000000
25%,19669.750000,1.000000,29.000000,3.000000,3.000000,0.000000,0.000000,51.000000,0.000000
50%,39225.500000,1.000000,33.000000,3.000000,5.000000,0.000000,0.000000,60.000000,0.000000
75%,58730.500000,1.000000,39.000000,4.000000,7.000000,1.000000,0.000000,76.000000,0.000000
max,78298.000000,10.000000,60.000000,5.000000,37.000000,1.000000,1.000000,99.000000,1.000000

In [2]:
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [3]:
df.tail()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
54803,3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,0,78,0
54804,74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,0,56,0
54805,13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,1,0,79,0
54806,13614,Sales & Marketing,region_9,NaN,m,sourcing,1,29,1.0,2,0,0,45,0
54807,51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,0,49,0

In [ ]:
# Extraer los nombres de las columnas numéricas
columnas_numericas = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
# Extraer los nombres de las columnas categóricas
columnas_categoricas = df.select_dtypes(include=['object', 'category', 'bool', 'str']).columns.tolist()
print("Variables Numéricas:")
print(columnas_numericas)
print("\nVariables Categóricas:")
print(columnas_categoricas)

Variables Numéricas:
['employee_id', 'no_of_trainings', 'age', 'previous_year_rating', 'length_of_service', 'KPIs_met >80%', 'awards_won?', 'avg_training_score', 'is_promoted']

Variables Categóricas:
['department', 'region', 'education', 'gender', 'recruitment_channel']

In [ ]:
# Crear una función para reutilizarla si es necesario
def resumen_datos(dataframe):
    total_filas = len(dataframe)
    
    # Calcular absolutos
    vacios = dataframe.isnull().sum()
    poblados = dataframe.notnull().sum()
    
    # Calcular porcentajes
    pct_vacios = (vacios / total_filas) * 100
    pct_poblados = (poblados / total_filas) * 100
    
    # Estructurar los resultados en un nuevo DataFrame
    resumen_df = pd.DataFrame({
        'Total Registros': total_filas,
        'Poblados (#)': poblados,
        'Poblados (%)': pct_poblados.round(2), # Redondear a 2 decimales
        'Vacíos (#)': vacios,
        'Vacíos (%)': pct_vacios.round(2)
    })
    
    # Ordenar de mayor a menor según la cantidad de vacíos para visualizar los más problemáticos primero
    resumen_df = resumen_df.sort_values(by='Vacíos (#)', ascending=False)
    
    return resumen_df

# Aplicar la función a tu DataFrame 'df'
analisis_columnas = resumen_datos(df)

# Mostrar el resultado (display funciona mejor en Jupyter Notebooks)
display(analisis_columnas)

,Total Registros,Poblados (#),Poblados (%),Vacíos (#),Vacíos (%)
previous_year_rating,54808,50684,92.48,4124,7.52
education,54808,52399,95.60,2409,4.40
department,54808,54808,100.00,0,0.00
region,54808,54808,100.00,0,0.00
gender,54808,54808,100.00,0,0.00
employee_id,54808,54808,100.00,0,0.00
recruitment_channel,54808,54808,100.00,0,0.00
no_of_trainings,54808,54808,100.00,0,0.00
age,54808,54808,100.00,0,0.00
length_of_service,54808,54808,100.00,0,0.00
KPIs_met >80%,54808,54808,100.00,0,0.00
awards_won?,54808,54808,100.00,0,0.00
avg_training_score,54808,54808,100.00,0,0.00
is_promoted,54808,54808,100.00,0,0.00